---
title: "correction_testing"
output:
  html_document: 
    toc: true
    toc_float: true
date: "2025-09-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
devtools::load_all()

library(KAMP)
#library(devtools)
library(tidyverse)
library(spatstat.random)
library(microbenchmark)
library(spatstat.geom)
library(spatstat.explore)
library(ggplot2)
library(Rcpp)
library(kableExtra)

set.seed(50)
```

# Setup
Importing data
```{r}
ids <- unique(ovarian_df$sample_id)
marksvar <- "immune"

for (id in ids) {
  df_sub <- ovarian_df %>% filter(sample_id == id)
  w <- convexhull.xy(df_sub$x, df_sub$y)
  pp_obj <- ppp(df_sub$x, df_sub$y, window = w, marks = df_sub[[marksvar]])
  
  p <- ggplot(as_tibble(pp_obj), aes(x, y, color = marks)) +
    geom_point(size = 0.6) +
    labs(title = paste("Sample:", id)) +
    theme_minimal()
  
  print(p)
}
```

```{r}
ids <- unique(ovarian_df$sample_id)
df <- ovarian_df %>% filter(sample_id == ids[2]) # 4 has 8k points, 2 has > 10000
mark_var <- "immune"
head(df)

nrow(df)
```

# Simulation

## Setup

```{r, eval = FALSE}
library(KAMP)
library(tidyverse)
library(microbenchmark)
library(spatstat.geom)
library(spatstat.explore)
library(ggplot2)
library(Rcpp)
library(parallel)
```



```{r}
# Kinhom helper since that's not in the package - since sim_data comes as a ppp don't need to convert, but basically copy paste expectation code here

kinhom_estimates <- function(ppp_obj, rvals, mark_var, mark1, correction) {
  kinhom_result <- Kinhom(ppp_obj, r = rvals, correction = correction)
  kinhom_df <- as_tibble(kinhom_result$data) %>%
    select(r, theo_csr = theo) %>%
    mutate(kinhom = theo - rvals^2 * pi)
  
  return(kinhom_df)
}


```

```{r}
set.seed(50)
n_values <- c(500, 1000, 5000)
abundance_values <- c(0.1, 0.3)
distribution_values <- "inhom"
clust_values <- c(TRUE, FALSE)
correction <- c("trans", "iso")
univariate <- FALSE


param_grid <- expand.grid(n = n_values,
                          abundance = abundance_values,
                          distribution = distribution_values,
                          clust = clust_values,
                          correction = correction,
                          univariate = univariate,
                          stringsAsFactors = FALSE)
head(param_grid)




results_list_rcpp_false <- list()
results_list_rcpp_true <- list()

run_parallel <- FALSE

if (run_parallel) {
  no_cores <- max(1, detectCores() - 1)
  cl <- makeCluster(no_cores)

  clusterEvalQ(cl, {
    library(KAMP)
  })

  clusterExport(
    cl,
    varlist = c("param_grid", "kamp"),
    envir = environment()
  )

  clusterSetRNGStream(cl, iseed = 50)

  out <- parLapply(cl, 1:nrow(param_grid), function(i) {
    params <- param_grid[i, ]

    # simulate ONCE
    if (params$univariate) {
      sim_data <- KAMP::sim_pp_data(
        lambda_n = params$n,
        abundance = params$abundance,
        markvar1 = "immune",
        markvar2 = "background",
        distribution = params$distribution,
        clust = params$clust
      )
      mark_var <- "marks"
      mark1 <- "immune"
      mark2 <- NULL
    } else {
      sim_data <- KAMP::sim_pp_data_biv(
        lambda_n = params$n,
        abundance = params$abundance,
        markvar1 = "immune1",
        markvar2 = "immune2",
        markvar3 = "background",
        distribution = params$distribution,
        clust = params$clust
      )
      mark_var <- "marks"
      mark1 <- "immune1"
      mark2 <- "immune2"
    }

    dat <- as.data.frame(sim_data)
    rvals <- seq(0, 0.5, by = 0.05)

    # run Rcpp = FALSE
    timing_false <- system.time({
      df_false <- kamp(
        dat,
        rvals = rvals,
        univariate = params$univariate,
        mark_var = mark_var,
        mark1 = mark1,
        mark2 = mark2,
        correction = params$correction,
        variance = TRUE,
        Rcpp = FALSE
      )
    })

    # run Rcpp = TRUE
    timing_true <- system.time({
      df_true <- kamp(
        dat,
        rvals = rvals,
        univariate = params$univariate,
        mark_var = mark_var,
        mark1 = mark1,
        mark2 = mark2,
        correction = params$correction,
        variance = TRUE,
        Rcpp = TRUE
      )
    })

    list(
      false = list(
        df = df_false,
        params = params,
        runtime_sec = as.numeric(timing_false["elapsed"])
      ),
      true = list(
        df = df_true,
        params = params,
        runtime_sec = as.numeric(timing_true["elapsed"])
      )
    )
  })

  stopCluster(cl)

  results_list_rcpp_false <- lapply(out, `[[`, "false")
  results_list_rcpp_true  <- lapply(out, `[[`, "true")
  
} else {
  results_list_rcpp_false <- list()
  results_list_rcpp_true <- list()
  for (i in 1:nrow(param_grid)) {
    params <- param_grid[i, ]
    
    if (params$univariate) {
      sim_data <- KAMP::sim_pp_data(lambda_n = params$n,
                                    abundance = params$abundance,
                                    markvar1 = "immune",
                                    markvar2 = "background",
                                    distribution = params$distribution,
                                    clust = params$clust)
      mark_var <- "marks"
      mark1 <- "immune"
      mark2 <- NULL
    } else {
      sim_data <- KAMP::sim_pp_data_biv(lambda_n = params$n,
                                        abundance = params$abundance,
                                        markvar1 = "immune1",
                                        markvar2 = "immune2",
                                        markvar3 = "background",
                                        distribution = params$distribution,
                                        clust = params$clust)
      mark_var <- "marks"
      mark1 <- "immune1"
      mark2 <- "immune2"
    }
    
    # messsage curr sim number
    message(paste0("Running simulation ", i, " of ", nrow(param_grid)))
    
    timing_rcpp_false <- system.time({
      df_rcpp_false <- kamp(
        as.data.frame(sim_data), 
        rvals = seq(0, 0.5, by = 0.05),
        univariate = params$univariate,
        mark_var = mark_var,
        mark1 = mark1,
        mark2 = mark2,
        correction = params$correction,
        variance = TRUE,
        Rcpp = FALSE
      )
    })
    
    timing_rcpp_true <- system.time({
      df_rcpp_true <- kamp(
        as.data.frame(sim_data), 
        rvals = seq(0, 0.5, by = 0.05),
        univariate = params$univariate,
        mark_var = mark_var,
        mark1 = mark1,
        mark2 = mark2,
        correction = params$correction,
        variance = TRUE,
        Rcpp = TRUE
      )
    })
    
    result_rcpp_false <- list(
      df = df_rcpp_false,      
      params = params, 
      runtime_sec = as.numeric(timing_rcpp_false["elapsed"])
    )
    
    result_rcpp_true <- list(
      df = df_rcpp_true,      
      params = params, 
      runtime_sec = as.numeric(timing_rcpp_true["elapsed"])
    )
    
    results_list_rcpp_false[[i]] <- result_rcpp_false
    results_list_rcpp_true[[i]] <- result_rcpp_true
  }
}

# save results

saveRDS(results_list_rcpp_false, file = "results_list_rcpp_false.rds")
saveRDS(results_list_rcpp_true, file = "results_list_rcpp_true.rds")
```


LOAD TO TEST
```{r}
rcpp_false_results <- readRDS("results_list_rcpp_false.rds")
rcpp_true_results <- readRDS("results_list_rcpp_true.rds")
```


Design for large simulation study:
- n = (500, 1000, 5000)
- Abundance = (0.1, 0.3)
- clust = (TRUE, FALSE)
- correction = (trans, iso)
- Bivariate inhomogenous
- reps = 100
- Rcpp = TRUE (for speed)
- Goal: compare K, Kinhom, KAMP, KAMP lite (thin_pct = 0.5)

Analyses (what are we comparing?)
- Computation time
- Degree of clustering

