// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kamp_pair_sums_bord
List kamp_pair_sums_bord(IntegerVector i, IntegerVector j, NumericVector d, NumericVector rvals, LogicalVector is_mark1, NumericVector bdist, int npts);
RcppExport SEXP _KAMP_kamp_pair_sums_bord(SEXP iSEXP, SEXP jSEXP, SEXP dSEXP, SEXP rvalsSEXP, SEXP is_mark1SEXP, SEXP bdistSEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rvals(rvalsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_mark1(is_mark1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    rcpp_result_gen = Rcpp::wrap(kamp_pair_sums_bord(i, j, d, rvals, is_mark1, bdist, npts));
    return rcpp_result_gen;
END_RCPP
}
// kamp_pair_sums_trans_iso
List kamp_pair_sums_trans_iso(IntegerVector i, IntegerVector j, NumericVector d, NumericVector w, NumericVector rvals, LogicalVector is_mark1, int npts);
RcppExport SEXP _KAMP_kamp_pair_sums_trans_iso(SEXP iSEXP, SEXP jSEXP, SEXP dSEXP, SEXP wSEXP, SEXP rvalsSEXP, SEXP is_mark1SEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rvals(rvalsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_mark1(is_mark1SEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    rcpp_result_gen = Rcpp::wrap(kamp_pair_sums_trans_iso(i, j, d, w, rvals, is_mark1, npts));
    return rcpp_result_gen;
END_RCPP
}
// kamp_pair_sums_trans_iso_biv
List kamp_pair_sums_trans_iso_biv(IntegerVector i, IntegerVector j, NumericVector d, NumericVector w, NumericVector rvals, LogicalVector is_mark1, LogicalVector is_mark2, int npts);
RcppExport SEXP _KAMP_kamp_pair_sums_trans_iso_biv(SEXP iSEXP, SEXP jSEXP, SEXP dSEXP, SEXP wSEXP, SEXP rvalsSEXP, SEXP is_mark1SEXP, SEXP is_mark2SEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rvals(rvalsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_mark1(is_mark1SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_mark2(is_mark2SEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    rcpp_result_gen = Rcpp::wrap(kamp_pair_sums_trans_iso_biv(i, j, d, w, rvals, is_mark1, is_mark2, npts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KAMP_kamp_pair_sums_bord", (DL_FUNC) &_KAMP_kamp_pair_sums_bord, 7},
    {"_KAMP_kamp_pair_sums_trans_iso", (DL_FUNC) &_KAMP_kamp_pair_sums_trans_iso, 7},
    {"_KAMP_kamp_pair_sums_trans_iso_biv", (DL_FUNC) &_KAMP_kamp_pair_sums_trans_iso_biv, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_KAMP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
