---
title: "4-23 Analysis"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(tidyverse)
library(doParallel)
library(foreach)
library(dplyr)
library(here)
library(tictoc)
library(spatstat)
library(kperm)
devtools::load_all()

library(scSpatialSIM)
set.seed(5000)
```

```{r}
type <- "inhom"
clust <- FALSE
marksvar = "immune"
rvalues <- seq(0, 1, length.out = 25)

# Scales by 10 since window size is 10x10 instead of 1x1
if (clust == TRUE) {
  rvalues <- rvalues * 10
} 


sim_data <- get_sim_data(lambda_n = 1000, 
                    abundance = 0.25,
                    type = type,
                    clust = clust)
marksvar = "immune"

#w = convexhull.xy(ovarian[["x"]], ovarian[["y"]])

# define pp_obj
# pp_obj = ppp(ovarian[["x"]], ovarian[["y"]], window = w, marks = ovarian[[marksvar]])

pp_obj <- sim_data

df_back <- as.data.frame(pp_obj) %>%
  as_tibble()

df_back

pp_obj$marks <- factor(pp_obj$marks, levels = c("background", "immune"))

as_tibble(pp_obj) %>%
  ggplot(aes(x, y, color = marks)) +
  geom_point()
```

```{r}

nperm = 1000

k = Kcross(pp_obj, i = "immune", j = "immune",
           r = rvalues,
           correction = c("trans"))

k = k %>%
  as_tibble() %>%
  mutate(method = "k") %>%
  select(r, csr = theo, trans, method)


kf = function(obj){
  kdf = Kcross(obj, i = "immune", j = "immune",
               r = rvalues,
               correction = c("trans"))
  as_tibble(kdf) %>% filter(r %in% rvalues) %>% select(r, trans)
}

perms = rlabel(pp_obj, nsim = nperm)
kperm = map_dfr(perms, kf)
kperm = kperm %>% group_by(r) %>% summarise(csr = mean(trans)) %>% ungroup() %>%
  mutate(trans = k$trans,
         method = "perm") %>%
  select(r, csr, trans, method)

kperm
```


```{r}
test = get_kamp_expectation(ppp_obj = pp_obj,
                            rvec = rvalues,
                            markvar = marksvar) %>% 
  mutate(og_fundiff = k - theo_csr,
         method = "kamp") %>%
  drop_na()

test



test_two <- get_kamp_variance(
      ppp_obj = sim_data,
      rvec = rvalues
    )

test_two
```

```{r}
wd = getwd()

if(substring(wd, 4, 8) == "Users"){
  doLocal = TRUE
  suppressPackageStartupMessages(library(doParallel))
  cl <- makeCluster(12)  
  registerDoParallel(cl)
}else{
  doLocal = FALSE
}

type <- c("inhom", "hom")
clust <- c(TRUE, FALSE)
n <- c(1000, 2000, 5000)
abundance <- c(0.1, 0.25, 0.5)

param_grid <- expand.grid(
  type = type,
  clust = clust,
  n = n,
  abundance = abundance
)

```

```{r}
kamp_results <- list()

for (i in 1:36) {
  file_path <- here("results", "expectation", "kamp", paste0("scenario_", i, ".RDA"))
  load(file_path) 
  results <- results %>%
    mutate(kamp_time = kamp_time * 25)
  kamp_results[[i]] <- results
}

combined_df <- bind_rows(kamp_results)

avg_times <- combined_df %>%
  group_by(type, abundance, n) %>%
  summarise(avg_kamp_time = mean(kamp_time), .groups = "drop")

ggplot(avg_times, aes(x = as.factor(abundance), y = avg_kamp_time)) + 
  geom_col(position = "dodge") +
  facet_wrap(~ n) +
  labs(
    title = "Average KAMP Computation Time",
    x = "Immune Cell Abundance",
    y = "Average Time (seconds)"
  ) +
  theme_minimal()
```

```{r}
load(here("results", "expectation", "kamp", "scenario_3.RDA"))
load(here("results", "expectation", "perm", "scenario_3.RDA"))
```

```{r}
perm_results <- list()

rda_files <- list.files(
  here("results", "expectation", "perm"),
  pattern = "\\.RDA$",
  full.names = TRUE
)

for (file in rda_files) {
  load(file)
  perm_results[[file]] <- results
}

combined_df <- bind_rows(perm_results)

avg_times <- combined_df %>%
  group_by(type, clust, abundance, n) %>%
  summarise(avg_perm_time = mean(kperm_time), .groups = "drop")

ggplot(avg_times, aes(x = as.factor(abundance), y = avg_perm_time, fill = as.factor(clust))) +
  geom_col(position = "dodge") +
  facet_wrap(~ n) +
  labs(
    title = "Average Perm Computation Time",
    x = "Immune Cell Abundance",
    y = "Average Time (seconds)",
    fill = "Clustering"
  ) +
  theme_minimal()
```

