utils::globalVariables(c("trans",
                         "kamp_fundiff",
                         "kamp_csr",
                         "r",
                         "theo_csr",
                         "x",
                         "y",
                         "rvalue",
                         "markvar",
                         "marks",
                         "Cell 1 Assignment",
                         "Hole Assignment",
                         "hole",
                         "immune",
                         "k"))
