# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kamp_pair_sums_bord <- function(i, j, d, rvals, is_mark1, bdist, npts) {
    .Call(`_KAMP_kamp_pair_sums_bord`, i, j, d, rvals, is_mark1, bdist, npts)
}

kamp_pair_sums_trans_iso <- function(i, j, d, w, rvals, is_mark1, npts) {
    .Call(`_KAMP_kamp_pair_sums_trans_iso`, i, j, d, w, rvals, is_mark1, npts)
}

kamp_pair_sums_trans_iso_biv <- function(i, j, d, w, rvals, is_mark1, is_mark2, npts) {
    .Call(`_KAMP_kamp_pair_sums_trans_iso_biv`, i, j, d, w, rvals, is_mark1, is_mark2, npts)
}

