# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kamp_pair_sums_trans <- function(i, j, d, w, rvals, is_mark1, npts) {
    .Call(`_KAMP_kamp_pair_sums_trans`, i, j, d, w, rvals, is_mark1, npts)
}

kamp_pair_sums_trans_biv <- function(i, j, d, w, rvals, is_mark1, is_mark2, npts) {
    .Call(`_KAMP_kamp_pair_sums_trans_biv`, i, j, d, w, rvals, is_mark1, is_mark2, npts)
}

